brain_area_dict = {
    "all": [
        # AMYGDALA
        "amy",
        "amygdala",
        "Amygdala",
        "AMY",
        # HIPPOCAMPUS
        "hpc",
        "hippocampus",
        "Hippocampus",
        "HPC",
        # PARAHIPPOCAMPAL CORTEX
        "parahippocampal_gyrus",
        "parahippocampal_cortex",
        "PHC",
        "phc",
        # ORBITOFRONTAL CORTEX
        "ofc",
        "orbitofrontal cortex",
        "OFC",
        # ANTERIOR CINGULATE CORTEX
        "acc",
        "ACC",
        "anterior cingulate cortex",
        # DORSAL ANTERIOR CINGULATE CORTEX
        "dorsal_anterior_cingulate_cortex",
        "dACC",
        # SUPPLEMENTARY MOTOR AREA
        "sma",
        "SMA",
        "supplementary motor area",
        # PRE-SUPPLEMENTARY MOTOR AREA
        "presma",
        "preSMA",
        "pre-supplementary motor area",
        "pre_supplementary_motor_area",
        # VENTROMEDIAL PREFRONTAL CORTEX
        "vmpfc",
        "vmPFC",
        "ventromedial prefrontal cortex",
        "ventral_medial_prefrontal_cortex",
    ],
    "mtl": [
        "amy",
        "AMY",
        "amygdala",
        "Amygdala",
        "hpc",
        "HPC",
        "hippocampus",
        "Hippocampus",
    ],
    "amygdala": ["amy", "AMY", "amygdala", "Amygdala"],
    "amy": ["amy", "AMY", "amygdala", "Amygdala"],
    "hippocampus": ["hpc", "HPC", "hippocampus", "Hippocampus"],
    "hpc": ["hpc", "HPC", "hippocampus", "Hippocampus"],
    "orbitofrontal cortex": ["orbitofrontal cortex", "ofc", "OFC"],
    "ofc": ["orbitofrontal cortex", "ofc", "OFC"],
    "anterior cingulate cortex": ["anterior cingulate cortex", "acc", "ACC"],
    "acc": ["anterior cingulate cortex", "acc", "ACC"],
    "ACC": ["anterior cingulate cortex", "acc", "ACC"],
    "supplementary motor area": ["supplementary motor area", "SMA", "sma"],
    "sma": ["supplementary motor area", "SMA", "sma"],
    "presma": ["pre-supplementary motor area", "preSMA", "presma"],
    "vmpfc": ["ventromedial prefrontal cortex", "vmPFC", "vmpfc"],
}
brain_area_abbreviations_upper = {
    "anterior cingulate cortex": "ACC",
    "dorsal_anterior_cingulate_cortex": "dACC",
    "ACC": "ACC",
    "all": "ALL",
    "Amygdala": "AMY",
    "amygdala": "AMY",
    "Hippocampus": "HPC",
    "hippocampus": "HPC",
    "orbitofrontal cortex": "OFC",
    "parahippocampal_cortex": "PHC",
    "parahippocampal_gyrus": "PHC",
    "pre_supplementary_motor_area": "preSMA",
    "preSMA": "preSMA",
    "supplementary motor area": "SMA",
    "ventral_medial_prefrontal_cortex": "vmPFC",
    "vmPFC": "vmPFC",
    "RSPE": "RSPE",
}
brain_area_abbreviations_lower = {
    "anterior cingulate cortex": "acc",
    "dorsal_anterior_cingulate_cortex": "dacc",
    "ACC": "acc",
    "all": "all",
    "Amygdala": "amy",
    "amygdala": "amy",
    "Hippocampus": "hpc",
    "hippocampus": "hpc",
    "orbitofrontal cortex": "ofc",
    "parahippocampal_cortex": "phc",
    "parahippocampal_gyrus": "phc",
    "preSMA": "presma",
    "pre_supplementary_motor_area": "presma",
    "supplementary motor area": "sma",
    "ventral_medial_prefrontal_cortex": "vmpfc",
    "vmPFC": "vmpfc",
    "RSPE": "rspe",
}
